version: '3.4'

services:
  ontime:
    image: ontime
    build:
      context: .
      dockerfile: ./Dockerfile
      
    environment:
      - PORT=${PORT}
    env_file:
      - .env.production
    ports:
      - '3000:3000'
    
 
